name: "[Bug Report] Windows Application - Intel® Arc™ & Iris® Xe Graphics"
description: "Intel® Arc™ A-Series, Arc™ B-Series, Iris® Xe Graphics and Intel® Core™ Ultra Processors with Intel® Arc™ Graphics."
labels: 'Info: Needs Replication'
assignees: 'Felipe-Intel'
body:
  - type: markdown
    attributes:
      value: |
        > [!IMPORTANT]
        > Fields marked with asterisk (*) are required.
  - type: markdown
    attributes:
      value: '---'
  - type: checkboxes
    attributes:
      label: Requirements
      options:
        - label: Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates)
          required: true
        - label: Application is not cracked
          required: true
  - type: markdown
    attributes:
      value: '---'
  - type: input
    attributes:
      label:  Application
      description: "Full name of the application"
    validations:
      required: true
  - type: markdown
    attributes:
      value: '---'
  - type: input
    attributes:
      label: Processor / Processor Number
    validations:
      required: true
  - type: input
    attributes:
      label: Graphic Card
    validations:
      required: true
  - type: markdown
    attributes:
      value: '---'
  - type: dropdown
    attributes:
      label: GPU Driver Version
      options:
        - 32.0.101.6877
        - 32.0.101.6876
        - 32.0.101.6874
        - 32.0.101.6795
        - 32.0.101.6793
        - 32.0.101.6790
        - 32.0.101.6739
        - 32.0.101.6737
        - 32.0.101.6734
        - 32.0.101.6732
        - 32.0.101.6653
        - 32.0.101.6651
        - 32.0.101.6647
        - Other (Please specify)
      default: 0
    validations:
      required: true
  - type: input
    attributes:
      label: Other GPU Driver version
      description: "Specify your GPU driver version, if not present on the list"
  - type: markdown
    attributes:
      value: '---'
  - type: dropdown
    attributes:
      label: Rendering API
      options:
        - Vulkan
        - OpenGL
        - DirectX 12
        - DirectX 11
        - DirectX 10
        - DirectX 9
        - DirectX 8
        - Older (DirectX 7 and lower)
        - Not applicable
      default: 0
    validations:
      required: true
  - type: markdown
    attributes:
      value: '---'
  - type: dropdown
    attributes:
      label: Windows Build
      options:
        - Windows 11 24H2
        - Windows 11 23H2
        - Windows 11 22H2
        - Windows 11 21H2
        - Windows 10 22H2
        - Windows 10 21H2
        - Other (Please specify)
      default: 0
    validations:
      required: true
  - type: input
    attributes:
      label: Other Windows build
      description: "Specify your Windows build number, if not present on the list"
  - type: markdown
    attributes:
      value: '---'
  - type: textarea
    attributes:
      label: Intel System Support Utility report
      description: |
        Please generate and attach the output of Intel® System Support Utility here.

        See: [How to generate Intel System Support Utility report - IGCIT Wiki](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/How-to-generate-Intel-System-Support-Utility-report)
    validations:
      required: true
  - type: markdown
    attributes:
      value: '---'
  - type: textarea
    attributes:
      label: Description and steps to reproduce
      description: |
        Make sure you describe the issue and steps to reproduce accurately.

        In addition, if possible, please attach a video showing the issue.
    validations:
      required: true
  - type: markdown
    attributes:
      value: '---'
  - type: input
    attributes:
      label: Device / Platform
      description: "Share your device / platform name. It could be there is a specific constructor issue. [Recommended]"
  - type: markdown
    attributes:
      value: '---'
  - type: textarea
    attributes:
      label: Crash dumps
      description: "For more help see: [How to obtain crash dumps - IGCIT Wiki](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/How-to-obtain-crash-dumps)"
  - type: markdown
    attributes:
      value: '---'
  - type: textarea
    attributes:
      label: Application / Windows logs
      description: "If available, can help Intel engineers to identify and fix the issue faster"
