name: "[Bug Report] Windows Application - Intel® Arc™ & Iris® Xe Graphics"
description: "Intel® Arc™ A-Series, Arc™ B-Series, Iris® Xe Graphics and Intel® Core™ Ultra Processors with Intel® Arc™ Graphics."
labels: 'Info: Needs Replication'
assignees: 'Felipe-Intel'
body:
  - type: markdown
    attributes:
      value: |
        **Note: Once submitted, you can edit some of its fields, like checkboxes, directly, ie you don't need to use the Edit button**
  - type: markdown
    attributes:
      value: '---'
  - type: checkboxes
    attributes:
      label: Checklist [README]
      description: "Please take a moment to review this checklist before completing the form."
      options:
        - label: Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
          required: true
        - label: Application is not cracked
          required: true
  - type: markdown
    attributes:
      value: '---'
  - type: input
    attributes:
      label:  Application [Required]
      description: "Full name of the application"
    validations:
      required: true
  - type: markdown
    attributes:
      value: '---'
  - type: input
    attributes:
      label: Processor / Processor Number [Required]
    validations:
      required: true
  - type: input
    attributes:
      label: Graphic Card [Required]
    validations:
      required: true
  - type: markdown
    attributes:
      value: '---'
  - type: dropdown
    attributes:
      label: GPU Driver Version [Required]
      options:
        - 32.0.101.6460_101.6259
        - 32.0.101.6458_101.6257
        - 32.0.101.6449_101.6256
        - 32.0.101.6332_101.6253
        - 32.0.101.6325_101.6253
        - 32.0.101.6325_101.6252
        - 32.0.101.6319
        - 32.0.101.6314
        - 32.0.101.6299
        - 32.0.101.6297
        - 32.0.101.6130_101.6048
        - 32.0.101.6129_101.6045
        - 32.0.101.6127_101.6044
        - 32.0.101.6078_101.5736
        - 32.0.101.6078
        - Other (Please specify)
      default: 0
    validations:
      required: true
  - type: input
    attributes:
      label: Other GPU Driver version
      description: "Specify your GPU driver version, if not present on the list"
  - type: markdown
    attributes:
      value: '---'
  - type: dropdown
    attributes:
      label: Rendering API [Required]
      options:
        - Vulkan
        - OpenGL
        - DirectX12
        - DirectX11
        - DirectX10
        - DirectX9
        - DirectX8
        - Not applicable
      default: 0
    validations:
      required: true
  - type: markdown
    attributes:
      value: '---'
  - type: dropdown
    attributes:
      label: Windows Build [Required]
      options:
        - Windows 11 24H2
        - Windows 11 23H2
        - Windows 11 22H2
        - Windows 11 21H2
        - Windows 10 22H2
        - Windows 10 21H2
        - Other (Please specify)
      default: 0
  - type: input
    attributes:
      label: Other Windows build
      description: "Specify your Windows build number, if not present on the list"
  - type: markdown
    attributes:
      value: '---'
  - type: textarea
    attributes:
      label: Intel System Support Utility report
      description: |
        Please generate and attach the output of Intel® System Support Utility here.

        See: [How to generate Intel System Support Utility report - IGCIT Wiki](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/How-to-generate-Intel-System-Support-Utility-report)
      placeholder: "Tip: You can attach images, .mp4 videos, or files, by clicking this area to highlight it and then dragging files in."
    validations:
      required: true
  - type: markdown
    attributes:
      value: '---'
  - type: textarea
    attributes:
      label: Description and steps to reproduce [Required]
      description: |
        Make sure you describe the issue and steps to reproduce accurately.

        In addition, if possible, please attach a video showing the issue.
      placeholder: "Tip: You can attach images, .mp4 videos, or files, by clicking this area to highlight it and then dragging files in."
    validations:
      required: true
  - type: markdown
    attributes:
      value: '---'
  - type: input
    attributes:
      label: Device / Platform
      description: "Share your device / platform name. It could be there is a specific constructor issue. [Recommended]"
  - type: markdown
    attributes:
      value: '---'
  - type: textarea
    attributes:
      label: Crash dumps [Required, if applicable]
      description: "For more help see: [How to obtain crash dumps - IGCIT Wiki](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/How-to-obtain-crash-dumps)"
      placeholder: |
        Tip: You can attach files by clicking this area to highlight it and then dragging files in.

        Attach your compressed (*.zip*) dump here.
  - type: markdown
    attributes:
      value: '---'
  - type: textarea
    attributes:
      label: Application / Windows logs
      description: "if available, could help solve the issue faster. [Optional]"
      placeholder: |
        Tip: You can attach files by clicking this area to highlight it and then dragging files in.

        Attach your compressed (*.zip*) logs here.
