name: "[Bug Report] Windows Game - Intel® Integrated Graphics ( 7th - 10th Gen )"
description: "Report issues in Windows games for 7th-10th Gen Intel® Core™ Processor Graphics, and related Intel Atom®, Pentium®, and Celeron® processors."
labels: 'Info: Needs Replication'
assignees: 'Felipe-Intel'
body:
  - type: markdown
    attributes:
      value: |
        **Note: Once submitted, you can edit some of its fields, like checkboxes, directly, ie you don't need to use the Edit button**
  - type: markdown
    attributes:
      value: '---'
  - type: checkboxes
    attributes:
      label: Checklist [README]
      description: "Please take a moment to review this checklist before completing the form."
      options:
        - label: Device is not undervolted nor overclocked
          required: true
        - label: Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
          required: true
        - label: Game is not cracked, modded and use the latest patch
          required: true
  - type: markdown
    attributes:
      value: '---'
  - type: input
    attributes:
      label: Game [Required]
      description: "Full name of the game"
    validations:
      required: true
  - type: markdown
    attributes:
      value: '---'
  - type: checkboxes
    attributes:
      label: Game Platform [Required]
      options:
        - label: Steam
        - label: Microsoft Store / Gamepass
        - label: GOG Galaxy
        - label: Ubisoft Connect
        - label: Battle.net
        - label: Epic Games
        - label: Rockstar Games Launcher
        - label: EA app
        - label: Amazon Games app
        - label: Other (please specify)
  - type: input
    attributes:
      label: Other game platform
      description: "Specify your game platform if not present on the list"
  - type: markdown
    attributes:
      value: '---'
  - type: input
    attributes:
      label: Processor / Processor Number [Required]
    validations:
      required: true
  - type: markdown
    attributes:
      value: '---'
  - type: dropdown
    attributes:
      label: GPU Driver Version [Required]
      options:
        - 31.0.101.2134
        - 31.0.101.2130
        - 31.0.101.2128
        - 31.0.101.2127
        - 31.0.101.2125
        - 31.0.101.2121
        - Other (Please specify)
      default: 0
    validations:
      required: true
  - type: input
    attributes:
      label: Other GPU Driver version
      description: "Specify your GPU driver version, if not present on the list"
  - type: markdown
    attributes:
      value: '---'
  - type: dropdown
    attributes:
      label: Rendering API [Required]
      options:
        - Vulkan
        - OpenGL
        - DirectX12
        - DirectX11
        - DirectX10
        - DirectX9
        - DirectX8
        - Not applicable
      default: 0
    validations:
      required: true
  - type: markdown
    attributes:
      value: '---'
  - type: dropdown
    attributes:
      label: Windows Build [Required]
      options:
        - Windows 11 24H2
        - Windows 11 23H2
        - Windows 11 22H2
        - Windows 11 21H2
        - Windows 10 22H2
        - Windows 10 21H2
        - Other (Please specify)
      default: 0
  - type: input
    attributes:
      label: Other Windows build
      description: "Specify your Windows build number if not present on the list"
  - type: markdown
    attributes:
      value: '---'
  - type: textarea
    attributes:
      label: Intel System Support Utility report
      description: |
        Please generate and attach the output of Intel® System Support Utility here.

        See: [How to generate Intel System Support Utility report - IGCIT Wiki](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/How-to-generate-Intel-System-Support-Utility-report)
      placeholder: "Tip: You can attach images, .mp4 videos, or files, by clicking this area to highlight it and then dragging files in."
    validations:
      required: true
  - type: markdown
    attributes:
      value: '---'
  - type: textarea
    attributes:
      label: Description and steps to reproduce [Required]
      description: |
        Make sure you describe the issue and steps to reproduce accurately.

        In addition, if possible, please attach a video showing the following:

        * The start of the game from Windows
        * Your game settings
        * The issue you encountered
      placeholder: "Tip: You can attach images, .mp4 videos, or files, by clicking this area to highlight it and then dragging files in."
    validations:
      required: true
  - type: markdown
    attributes:
      value: '---'
  - type: checkboxes
    attributes:
      label: Game graphic quality [Required]
      options:
        - label: Low
        - label: Medium
        - label: High
        - label: Ultra
    validations:
      required: true
  - type: markdown
    attributes:
      value: '---'
  - type: input
    attributes:
      label: Game resolution [Required]
      description: "Specify your game resolution (1280x720, 1920x1080, ...)"
    validations:
      required: true
  - type: markdown
    attributes:
      value: '---'
  - type: dropdown
    attributes:
      label: Game VSync [Required]
      options:
        - "On"
        - "Off"
    validations:
      required: true
  - type: markdown
    attributes:
      value: '---'
  - type: checkboxes
    attributes:
      label: Game display mode [Required]
      options:
        - label: Fullscreen
        - label: Windowed
        - label: Borderless Windowed
    validations:
      required: true
  - type: markdown
    attributes:
      value: '---'
  - type: textarea
    attributes:
      label: Detailed game settings [Required]
      description: |
        Please, share your game settings.

        You can attach screenshots of the game setting screens or list them.
      placeholder: "Tip: You can attach images or files by clicking this area to highlight it and then dragging files in."
    validations:
      required: true
  - type: markdown
    attributes:
      value: '---'
  - type: input
    attributes:
      label: Device / Platform name
      description: "Share your device / platform name. It could be there is a specific constructor issue. [Recommended]"
  - type: markdown
    attributes:
      value: '---'
  - type: textarea
    attributes:
      label: Crash dumps [Required, if applicable]
      description: "For more help see: [How to obtain crash dumps - IGCIT Wiki](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/How-to-obtain-crash-dumps)"
      placeholder: |
        Tip: You can attach files by clicking this area to highlight it and then dragging files in.

        Attach your compressed (*.zip*) dump here.
  - type: markdown
    attributes:
      value: '---'
  - type: textarea
    attributes:
      label: Save game
      description: "if possible, could help solve the issue faster. [Optional]"
      placeholder: |
        Tip: You can attach files by clicking this area to highlight it and then dragging files in.

        Attach your compressed (.zip) save here.
