name: "[Bug Report] Display/Audio issue"
description: "Single and multi-monitor setup issues: resolution, refresh rate, VRR, display interfaces and display audio."
labels: 'Bug Type: Display/Audio'
body:
  - type: markdown
    attributes:
      value: |
        > [!IMPORTANT]
        > Fields marked with asterisk (*) are required.
  - type: markdown
    attributes:
      value: '---'
  - type: checkboxes
    attributes:
      label: Requirements
      options:
        - label: Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates)
          required: true
  - type: markdown
    attributes:
      value: '---'
  - type: input
    attributes:
      label: Processor / Processor Number
    validations:
      required: true
  - type: input
    attributes:
      label: Graphic Card
    validations:
      required: true
  - type: input
    attributes:
      label: Number of connected monitors
    validations:
      required: true
  - type: markdown
    attributes:
      value: '---'
  - type: dropdown
    attributes:
      label: GPU Driver Version
      options:
        - 32.0.101.8626
        - 32.0.101.8531
        - 32.0.101.8509
        - 32.0.101.8425_101.8362
        - 32.0.101.8331
        - 32.0.101.8250
        - 32.0.101.8247
        - 32.0.101.8136
        - 32.0.101.8135
        - Other (Please specify)
      default: 0
    validations:
      required: true
  - type: input
    attributes:
      label: Other GPU Driver version
      description: "Specify your GPU driver version, if not present on the list"
  - type: markdown
    attributes:
      value: '---'
  - type: dropdown
    attributes:
      label: Windows Build
      options:
        - Windows 11 25H2
        - Windows 11 24H2
        - Windows 11 23H2
        - Windows 11 22H2
        - Windows 11 21H2
        - Windows 10 22H2
        - Windows 10 21H2
        - Other (Please specify)
      default: 0
    validations:
      required: true
  - type: input
    attributes:
      label: Other Windows build
      description: "Specify your Windows build number, if not present on the list"
  - type: markdown
    attributes:
      value: '---'
  - type: textarea
    attributes:
      label: Intel System Support Utility report
      description: |
        Please generate and attach the output of Intel® System Support Utility here.

        See: [How to generate Intel System Support Utility report - IGCIT Wiki](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/How-to-generate-Intel-System-Support-Utility-report)
    validations:
      required: true
  - type: markdown
    attributes:
      value: '---'
  - type: textarea
    attributes:
      label: Monitors description
      description: |
        For each monitor, please share:

        - Brand:
        - Model number:
        - Monitor maximum resolution:
        - Connection type (HDMI, DP, Adapter HDMI->DP or viceversa, etc..):
        - Resolution being set in Windows:
        - Windows display mode (duplicate, extend, etc..):
        - Orientation:
    validations:
      required: true
  - type: markdown
    attributes:
      value: '---'
  - type: textarea
    attributes:
      label: Description and steps to reproduce
      description: |
        Make sure you describe the issue and steps to reproduce accurately.

        In addition, if possible, please attach a video showing the issue.
    validations:
      required: true
  - type: markdown
    attributes:
      value: '---'
  - type: input
    attributes:
      label: Device
      description: "Share your device name."