name: Feature request
description: Request a feature.
labels: 'Type: Feature Request'
assignees: 'Arturo-Intel'
body:
  - type: markdown
    attributes:
      value: |
        > [!IMPORTANT]
        > Fields marked with asterisk (*) are required.
  - type: input
    attributes:
      label:  Application
      description: "Full name of the application that requires the feature"
    validations:
      required: true
  - type: markdown
    attributes:
      value: '---'
  - type: input
    attributes:
      label: Processor / Processor Number [Required]
    validations:
      required: true
  - type: input
    attributes:
      label: Graphic Card
    validations:
      required: true
  - type: markdown
    attributes:
      value: '---'
  - type: dropdown
    attributes:
      label: Rendering API
      options:
        - Vulkan
        - OpenGL
        - DirectX 12
        - DirectX 11
        - Not applicable
      default: 0
    validations:
      required: true
  - type: markdown
    attributes:
      value: '---'
  - type: dropdown
    attributes:
      label: Windows Build
      options:
        - Windows 11 25H2
        - Windows 11 24H2
        - Windows 11 23H2
        - Windows 11 22H2
        - Windows 11 21H2
        - Windows 10 22H2
        - Windows 10 21H2
        - Other (Please specify)
      default: 0
    validations:
      required: true
  - type: input
    attributes:
      label: Other Windows build
      description: "Specify your Windows build number if not present on the list"
  - type: markdown
    attributes:
      value: '---'
  - type: textarea
    attributes:
      label: Describe the feature
    validations:
      required: true
  - type: markdown
    attributes:
      value: '---'
  - type: textarea
    attributes:
      label: Additional notes
